# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: recommend.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'recommend.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0frecommend.proto\x12\x16techscout.recommend.v1\"2\n\x06Source\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\r\n\x05score\x18\x03 \x01(\x01\"0\n\x10RecommendRequest\x12\r\n\x05query\x18\x01 \x01(\t\x12\r\n\x05top_k\x18\x02 \x01(\x05\"4\n\x0e\x43ompareRequest\x12\r\n\x05query\x18\x01 \x01(\t\x12\x13\n\x0bproduct_ids\x18\x02 \x03(\t\"T\n\x11RecommendResponse\x12\x0e\n\x06\x61nswer\x18\x01 \x01(\t\x12/\n\x07sources\x18\x02 \x03(\x0b\x32\x1e.techscout.recommend.v1.Source\"R\n\x0f\x43ompareResponse\x12\x0e\n\x06\x61nswer\x18\x01 \x01(\t\x12/\n\x07sources\x18\x02 \x03(\x0b\x32\x1e.techscout.recommend.v1.Source2\xd0\x01\n\x10RecommendService\x12`\n\tRecommend\x12(.techscout.recommend.v1.RecommendRequest\x1a).techscout.recommend.v1.RecommendResponse\x12Z\n\x07\x43ompare\x12&.techscout.recommend.v1.CompareRequest\x1a\'.techscout.recommend.v1.CompareResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'recommend_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SOURCE']._serialized_start=43
  _globals['_SOURCE']._serialized_end=93
  _globals['_RECOMMENDREQUEST']._serialized_start=95
  _globals['_RECOMMENDREQUEST']._serialized_end=143
  _globals['_COMPAREREQUEST']._serialized_start=145
  _globals['_COMPAREREQUEST']._serialized_end=197
  _globals['_RECOMMENDRESPONSE']._serialized_start=199
  _globals['_RECOMMENDRESPONSE']._serialized_end=283
  _globals['_COMPARERESPONSE']._serialized_start=285
  _globals['_COMPARERESPONSE']._serialized_end=367
  _globals['_RECOMMENDSERVICE']._serialized_start=370
  _globals['_RECOMMENDSERVICE']._serialized_end=578
# @@protoc_insertion_point(module_scope)
